elems:

  - src:  ^(make\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage

  - src:  ^(modules)$
    dst:  /etc/portage/<1>
    only: f?portage

  - src:  ^(env/.+)$
    dst:  /etc/portage/<1>
    only: f?portage

  - src:  ^(package\.(?:env|use|keywords|mask|unmask)/.+)$
    dst:  /etc/portage/<1>
    only: f?portage

  - src:  ^(repo\.postsync\.d/.+)$
    dst:  /etc/portage/<1>
    perms: 755
    only: f?portage

  - src:  ^(repos\.conf/gentoo\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage

  - src:  ^(repos\.conf/vmware\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage && f?vmware-repo

  - src:  ^(repos\.conf/go\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage && f?go-repo

  - src:  ^(repos\.conf/rindeal\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage

  - src:  ^(repos\.conf/local\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage && f?local-repo

  - src:  ^(repos\.conf/crossdev\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage && f?crossdev

  - src:  ^(repos\.conf/apo\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage && f?apo-repo

  - src:  ^(repos\.conf/pentoo\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage && f?pentoo-repo

  - src:  ^(repos\.conf/haskell\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage && f?haskell-repo

  - src:  ^(repos\.conf/r\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage && f?r-repo

  - src:  ^(repos\.conf/haskell\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage && f?haskell-repo

  - src:  ^(g-sorcery\.cfg)$
    dst:  /etc/g-sorcery/<1>
    only: f?portage && f?g-sorcery

  - src:  ^eix/(eix-sync\.conf)$
    dst:  /etc/<1>
    only: f?portage && f?eix

  - src:  ^eix/rc/(.+)$
    dst:  /etc/eixrc/<1>
    only: f?portage && f?eix

  - src:  ^distccd\.conf$
    dst:  /etc/systemd/system/distccd.service.d/00gentoo.conf
    only: f?portage && f?distcc && f?systemd

  - src:  ^(distcc)_(hosts)$
    dst:  /etc/<1>/<2>
    only: f?distcc
