elems:

  - src:  (make\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage

  - src:  (modules)$
    dst:  /etc/portage/<1>
    only: f?portage

  - src:  (repos\.conf/gentoo\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage

  - src:  (repos\.conf/local\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage && f?local-repo

  - src:  (repos\.conf/crossdev\.conf)$
    dst:  /etc/portage/<1>
    only: f?portage && f?crossdev

  - src:  (g-sorcery\.cfg)$
    dst:  /etc/g-sorcery/<1>
    only: f?portage && f?g-sorcery

  - src:  eix/(eix-sync\.conf)$
    dst:  /etc/<1>
    only: f?portage && f?eix

  - src:  eix/rc/(.+)$
    dst:  /etc/eixrc/<1>
    only: f?portage && f?eix
